name: Static Checks

on:
  push:
    branches:
      - main
      - dev
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: ESLint Solidity
        run: yarn lint:sol
      - name: ESLint TypeScript
        run: yarn lint:ts

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Prettier Solidity
        run: yarn format:sol
      - name: Prettier TypeScript
        run: yarn format:ts
      - name: Prettier YAML
        run: yarn format:yml

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Build contracts
        run: yarn build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Test contracts
        run: yarn test
